//go:build js && wasm

package components

import (
	"fmt"
	"reflect"
	"syscall/js"
)

type Event struct{ v js.Value }

func (e *Event) init(v js.Value) { e.v = v }

// Value returns the underlying js.Value of the event.
func (e Event) Value() js.Value { return e.v }

// PreventDefault prevents the default action associated with the event.
func (e Event) PreventDefault() { e.v.Call("preventDefault") }

// StopPropagation stops the event from propagating further.
func (e Event) StopPropagation() { e.v.Call("stopPropagation") }

// Target returns the event target.
func (e Event) Target() js.Value { return e.v.Get("target") }

// CurrentTarget returns the current target of the event.
func (e Event) CurrentTarget() js.Value { return e.v.Get("currentTarget") }

// https://developer.mozilla.org/en-US/docs/Web/API/InputEvent
type EventInput struct{ Event }

// Data returns the characters generated by the input event.
func (e EventInput) Data() string { return e.v.Get("data").String() }

// InputType returns the type of input that generated the event.
func (e EventInput) InputType() string { return e.v.Get("inputType").String() }

// InputValue returns the current value of the input element.
func (e EventInput) InputValue() string { return e.Target().Get("value").String() }

// https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent
type EventMouse struct{ Event }

// ClientX returns the horizontal coordinate of the mouse pointer.
func (e EventMouse) ClientX() int { return e.v.Get("clientX").Int() }

// ClientY returns the vertical coordinate of the mouse pointer.
func (e EventMouse) ClientY() int { return e.v.Get("clientY").Int() }

// https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent
type EventKeyboard struct{ Event }

// Key returns the value of the key pressed by the user.
func (e EventKeyboard) Key() string { return e.v.Get("key").String() }

// Code returns the physical key on the keyboard.
func (e EventKeyboard) Code() string { return e.v.Get("code").String() }

// AltKey indicates whether the "Alt" key was pressed.
func (e EventKeyboard) AltKey() bool { return e.v.Get("altKey").Bool() }

// CtrlKey indicates whether the "Control" key was pressed.
func (e EventKeyboard) CtrlKey() bool { return e.v.Get("ctrlKey").Bool() }

// ShiftKey indicates whether the "Shift" key was pressed.
func (e EventKeyboard) ShiftKey() bool { return e.v.Get("shiftKey").Bool() }

// MetaKey indicates whether the "Meta" key was pressed.
func (e EventKeyboard) MetaKey() bool { return e.v.Get("metaKey").Bool() }

// Repeat indicates whether the key is being held down such that it is automatically repeating.
func (e EventKeyboard) Repeat() bool { return e.v.Get("repeat").Bool() }

type initer interface {
	init(js.Value)
}

type On map[string]any // map[string]func[T Event](*T)

func (o On) Apply(parent any) (func() error, error) {
	p := parent.(*js.Value)

	var removers []func() error
	for name, handler := range o {
		remove, err := o.applyEvent(p, name, handler)
		if err != nil {
			return func() error { return nil }, fmt.Errorf("failed to apply event %s: %w", name, err)
		}
		removers = append(removers, remove)
	}

	return func() error {
		for _, remove := range removers {
			if err := remove(); err != nil {
				return err
			}
		}

		return nil
	}, nil
}

func (o On) applyEvent(parent *js.Value, name string, handler any) (func() error, error) {
	hv := reflect.ValueOf(handler)
	ht := hv.Type()

	var h func(js.Value)

	if ht.Kind() == reflect.Func && ht.NumOut() == 0 {
		switch ht.NumIn() {
		case 0:
			h = func(js.Value) { hv.Call(nil) }
		case 1:
			et := ht.In(0)
			if et.Kind() == reflect.Pointer && et.Implements(reflect.TypeFor[initer]()) {
				h = func(v js.Value) {
					e := reflect.New(et.Elem())
					e.Interface().(initer).init(v)
					hv.Call([]reflect.Value{e})
				}
			}
		}
	}

	if h == nil {
		return func() error { return nil }, fmt.Errorf("invalid event handler of type %T for event %s", handler, name)
	}

	jsFunc := js.FuncOf(func(this js.Value, args []js.Value) any {
		h(args[0])
		return nil
	})

	parent.Call("addEventListener", name, jsFunc)
	return func() error {
		parent.Call("removeEventListener", name, jsFunc)
		jsFunc.Release()
		return nil
	}, nil
}
